//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int studentID { get; set; }
        public string studentName { get; set; }
        public string studentGender { get; set; }
        public string Address_ { get; set; }
    }
}
